website:
  title: TLG Catalog - Dev
  navbar:
    right:
      - text: "Dev"
        menu:
          - text: "Stable"
            href: "https://insightsengineering.github.io/tlg-catalog/stable"
      - icon: slack
        href: https://app.slack.com/client/T028PB489D3/
        aria-label: Slack
      - icon: github
        href: https://github.com/insightsengineering/tlg-catalog
        aria-label: Repository
